// Per-concept flashcards. Keyed by concept slug.
// { front: 'term or question', back: 'definition or answer' }

export const FLASHCARDS = {
  // ===== Module 1: Foundations =====
  'large-language-model-llm': { front: 'What is an LLM?', back: 'A neural network trained to predict the next token in a sequence. Capability emerges from scale plus post-training, not from a database of facts.' },
  'foundation-model': { front: 'Foundation model', back: 'A general-purpose model trained on broad data that can be adapted to many downstream tasks via prompting, retrieval, or fine-tuning.' },
  'frontier-model': { front: 'Frontier model', back: 'The current generation of largest, most capable foundation models. Defines the capability ceiling at any given time; the label shifts every 6-12 months.' },
  'model-family-generation': { front: 'Model family / generation', back: 'A vendor\'s grouped lineage (e.g., Claude Opus / Sonnet / Haiku across 4.x generations). Same training base; size determines cost and latency.' },
  'open-weight-model': { front: 'Open-weight model', back: 'A model whose trained weights are publicly downloadable and runnable locally. Llama, Mistral, Qwen, DeepSeek. Usually NOT "open source": training code and data rarely released.' },
  'closed-weight-model': { front: 'Closed-weight model', back: 'Accessible only through a vendor API. Claude, GPT, Gemini. Pay per token; data leaves your boundary.' },
  'parameters': { front: 'Parameters', back: 'The learned weights inside a model; counted in billions. Roughly correlates with capability but training data and methodology matter as much.' },
  'pre-training': { front: 'Pre-training', back: 'The initial massive training run on internet-scale text. Most expensive step; produces a base model that completes text but does not yet follow instructions.' },
  'post-training': { front: 'Post-training', back: 'Everything after pre-training: SFT, RLHF / DPO, safety training, tool-use training. Turns a base model into a usable assistant.' },
  'transformer-architecture': { front: 'Transformer architecture', back: 'Vaswani et al. 2017 design that underlies all modern LLMs. Self-attention plus feed-forward layers; the dominant architecture for sequence modeling.' },
  'self-attention': { front: 'Self-attention', back: 'Mechanism letting each token attend to every other token in the context. Captures relationships across arbitrary distances in the sequence.' },
  'multi-head-attention': { front: 'Multi-head attention', back: 'Running multiple attention computations in parallel with separate projections. Lets one layer capture different types of relationships simultaneously.' },
  'positional-encoding': { front: 'Positional encoding', back: 'How a transformer learns word order. Self-attention is order-blind; position must be injected explicitly. RoPE is the dominant 2026 scheme.' },
  'rope': { front: 'RoPE', back: 'Rotary Position Embedding. Encodes position by rotating Q/K vectors; generalizes better to long contexts than absolute encodings. Used in Llama, Claude, Mistral.' },
  'kv-cache': { front: 'KV cache', back: 'Cached attention key/value vectors during generation. Turns O(N) per-token work into O(1); the reason streaming feels fast.' },
  'mixture-of-experts-moe': { front: 'MoE (Mixture of Experts)', back: 'Architecture where each token activates only a subset of model parameters. Stores more knowledge than it pays for at inference time.' },
  'context-window': { front: 'Context window', back: 'Maximum number of tokens a model can attend to in one inference call. 2026 frontier: 200K-2M tokens.' },
  'logits': { front: 'Logits', back: 'Raw unnormalized scores the model produces for each vocabulary token before softmax. Range over reals; higher means more likely.' },
  'softmax': { front: 'Softmax', back: 'Function converting logits into a probability distribution. Each output positive; all outputs sum to 1.' },
  'token': { front: 'Token', back: 'The atomic unit a model reads and produces. Usually a subword fragment, not a whole word. ~0.75 English words per token on average.' },
  'tokenization': { front: 'Tokenization', back: 'Splitting text into tokens before feeding to the model. Deterministic preprocessing; turns strings into integer IDs.' },
  'bpe': { front: 'BPE', back: 'Byte-Pair Encoding. The dominant tokenization algorithm. Iteratively merges the most-frequent adjacent character pairs into vocabulary entries.' },
  'sentencepiece': { front: 'SentencePiece', back: 'Google\'s tokenizer library. Language-agnostic; treats text as raw Unicode. Used by Gemini, T5, mT5.' },
  'tiktoken': { front: 'Tiktoken', back: 'OpenAI\'s BPE implementation. Byte-level; eliminates the unknown-character problem. Open-source, fast.' },
  'vocabulary': { front: 'Vocabulary', back: 'The fixed set of tokens a model knows. Typically 32K to 256K entries; learned during tokenizer training.' },
  'tokenizer-as-pricing': { front: 'Tokenizer-as-pricing', back: 'Different models tokenize the same text into different counts. Same prompt costs different amounts across vendors. Always test on your actual data.' },
  'embedding': { front: 'Embedding', back: 'A dense vector representation of text. Two texts with similar meaning land near each other in the embedding space.' },
  'embedding-model': { front: 'Embedding model', back: 'A model trained to produce embeddings. Bi-encoder architecture: each text encoded independently into a fixed-size vector.' },
  'vector': { front: 'Vector', back: 'Ordered list of numbers representing data in n-dimensional space. The mathematical primitive underneath embeddings, attention, similarity search.' },
  'cosine-similarity': { front: 'Cosine similarity', back: 'Direction-only similarity between vectors. Equal to dot product if both vectors are unit-normalized. Standard for embedding comparisons.' },
  'dot-product': { front: 'Dot product', back: 'Sum of corresponding component products. For unit vectors, equals cosine of the angle between them. Workhorse of attention and retrieval.' },
  'euclidean-distance': { front: 'Euclidean distance', back: 'Straight-line distance between two vectors. Sensitive to magnitude; usually inferior to cosine for semantic similarity.' },
  'mrl': { front: 'MRL', back: 'Matryoshka Representation Learning. Produces embeddings whose shorter prefixes are also valid embeddings. Enables tier-1/tier-2 retrieval.' },
  'inference': { front: 'Inference', back: 'Running a trained model on new input to produce output. Memory-bandwidth-bound for most LLM workloads.' },
  'sampling': { front: 'Sampling', back: 'Picking the next token from the model\'s output distribution. Greedy = always argmax. Stochastic = draw according to distribution.' },
  'temperature': { front: 'Temperature', back: 'Scaling factor applied to logits before softmax. T=0: deterministic. T=1: model default. T>1: more uniform / creative.' },
  'top-p': { front: 'Top-p (nucleus sampling)', back: 'Restricts sampling to the smallest set of tokens whose cumulative probability exceeds P. Adapts the candidate set to model confidence.' },
  'top-k': { front: 'Top-k', back: 'Sampling restricted to the K most-likely tokens. Simpler than top-p but less adaptive; usually preferred over top-k is top-p.' },
  'latency': { front: 'Latency (LLM)', back: 'Time from request to response. TTFT (time-to-first-token) plus ITL (inter-token latency). Long inputs slow prefill; long outputs slow generation.' },
  'throughput': { front: 'Throughput', back: 'Tokens generated per second. Per-request and aggregate diverge under batching. vLLM / SGLang give 5-30x over naive serving.' },
  'quantization': { front: 'Quantization', back: 'Reducing the precision of model weights (FP16 -> INT8 / INT4) to save memory and bandwidth. AWQ and GGUF are the dominant 2026 formats.' },

  // ===== Module 2: Prompting Patterns =====
  'system-prompt': { front: 'System prompt', back: 'Persistent instructions sent at the start of every model conversation. Defines persona, rules, capabilities, constraints across all turns.' },
  'user-prompt': { front: 'User prompt', back: 'Input from the user in a conversation turn. Distinct from the system prompt: changes each turn while system holds.' },
  'assistant-message': { front: 'Assistant message', back: 'The model\'s output in a conversation turn. In multi-turn chat, prior assistant messages become context for subsequent turns.' },
  'prompt-template': { front: 'Prompt template', back: 'Reusable parametrized prompt where runtime values fill placeholders. Atomic unit of production prompt engineering.' },
  'zero-shot-prompting': { front: 'Zero-shot prompting', back: 'Asking the model to perform a task without examples. Modern frontier models handle most common tasks zero-shot at high quality.' },
  'few-shot-prompting': { front: 'Few-shot prompting', back: 'Providing 1-10 example input-output pairs to demonstrate the task. The most reliable way to teach a custom format or convention.' },
  'chain-of-thought-cot': { front: 'Chain-of-Thought (CoT)', back: 'Prompting the model to think step-by-step before producing the final answer. Improves accuracy on multi-step reasoning at the cost of more tokens.' },
  'tree-of-thoughts-tot': { front: 'Tree-of-Thoughts (ToT)', back: 'Generating multiple reasoning paths in parallel, evaluating each, continuing only the most promising. Search-based extension of CoT.' },
  'self-consistency': { front: 'Self-consistency', back: 'Sampling K independent CoT responses; taking the majority answer. Improves accuracy by averaging out reasoning errors.' },
  'prompt-chaining': { front: 'Prompt chaining', back: 'Decomposing a task into multiple sequential model calls. Simplest agentic pattern; each step has focused context.' },
  'structured-output': { front: 'Structured output', back: 'Forcing the model to produce output in a specific format (JSON, XML, YAML). Prompt-only, constrained decoding, or post-hoc validation.' },
  'json-mode': { front: 'JSON mode', back: 'Endpoint mode that constrains output to valid JSON. Implementation of constrained decoding; pair with a JSON Schema for shape enforcement.' },
  'pydantic': { front: 'Pydantic', back: 'Python\'s dominant data-validation library. Standard way to define schemas for LLM structured output.' },
  'instructor': { front: 'Instructor', back: 'Python library wrapping LLM clients with Pydantic-based structured output. Decorator turns "LLM call" into "typed object".' },
  'constrained-decoding': { front: 'Constrained decoding', back: 'Inference-time technique that masks tokens to enforce a grammar (JSON, regex, BNF). The mechanical foundation of structured-output modes.' },
  'negative-triggers-do-not-use-for': { front: 'Negative triggers', back: '"Do NOT use for..." instructions about when not to invoke a behavior. Prevents tool / Skill misuse; complement to positive triggers.' },
  'prompt-caching': { front: 'Prompt caching', back: 'Caching K-V state of a prompt prefix so subsequent same-prefix requests skip recomputation. 90% discount; major cost lever for repeat-prefix workloads.' },
  'inverse-scaling-at-test-time-compute': { front: 'Inverse scaling at test-time', back: 'Phenomenon where giving a model more thinking budget makes it perform worse on certain tasks. Reproducible; counterintuitive.' },
  'prompt-injection': { front: 'Prompt injection', back: 'Attacker embeds instructions in tool output, retrieved documents, or user input to override the system prompt. Dominant 2026 LLM security threat.' },
  'jailbreak': { front: 'Jailbreak', back: 'A prompt that bypasses safety training to elicit forbidden outputs. Targets the model\'s policy; injection targets the system prompt.' },
  'react': { front: 'ReAct', back: 'Reasoning + Action agent pattern. Model alternates between reasoning steps and tool calls until task is complete.' },

  // ===== Module 3: Context Engineering & RAG =====
  'context-engineering': { front: 'Context engineering', back: 'The 2026 reframe of "prompt engineering". Everything about getting the right information into the model\'s context window.' },
  'retrieval-augmented-generation-rag': { front: 'RAG', back: 'Retrieval-Augmented Generation. Retrieve relevant context, inject into prompt, generate answer grounded in that context.' },
  'naive-rag': { front: 'Naive RAG', back: 'Embed query, retrieve top-K, stuff into prompt. The starting point; quickly outgrown for production by Advanced RAG.' },
  'advanced-rag': { front: 'Advanced RAG', back: 'RAG with query rewriting, hybrid search, reranking, and multi-query expansion. The 2026 baseline production architecture.' },
  'modular-rag': { front: 'Modular RAG', back: 'RAG with composable, swappable retrieval modules. Treats retrieval as a graph of small components rather than a fixed pipeline.' },
  'graphrag': { front: 'GraphRAG', back: 'RAG augmented with a knowledge graph derived from the corpus. Better for queries requiring multi-hop reasoning.' },
  'agentic-rag': { front: 'Agentic RAG', back: 'Retrieval where an agent decides what to retrieve, when to retrieve, and how many times. Replaces fixed pipeline with iterative tool use.' },
  'chunking': { front: 'Chunking', back: 'Splitting documents into retrievable pieces. Strategy choices include fixed-size, semantic, late chunking, hierarchical.' },
  'chunk-size': { front: 'Chunk size', back: 'Tokens or characters per chunk. The most-tunable RAG hyperparameter. Sweep on your eval set; pick what maximizes answer quality.' },
  'chunk-overlap': { front: 'Chunk overlap', back: 'Tokens shared between adjacent chunks. Mitigates the boundary-cut problem when relevant content spans two chunks.' },
  'semantic-chunking': { front: 'Semantic chunking', back: 'Chunking strategy that respects semantic boundaries (sections, paragraphs, sentences) rather than fixed token counts. Higher quality; default in 2026.' },
  'late-chunking': { front: 'Late chunking', back: 'Embed full document first, then chunk the embedding. Chunks share document-level context that early-chunked embeddings lose.' },
  'vector-database': { front: 'Vector database', back: 'A database for ANN (approximate nearest-neighbor) search over vector embeddings. Pinecone, Qdrant, Weaviate, pgvector, etc.' },
  'pinecone': { front: 'Pinecone', back: 'A managed vector database. Pioneered the category around 2021; popular default for hosted production RAG.' },
  'weaviate': { front: 'Weaviate', back: 'Open-source vector database with built-in hybrid search and modular embedding generation. Self-hosted or managed.' },
  'qdrant': { front: 'Qdrant', back: 'Open-source Rust-native vector database. Fast, simple API, strong defaults. Popular 2026 self-hosted choice.' },
  'chroma': { front: 'Chroma', back: 'Embedded vector database designed for local development and small-to-medium production. SQLite-style ergonomics for AI builders.' },
  'lancedb': { front: 'LanceDB', back: 'Embedded columnar vector database backed by Lance (Parquet-derived format). Optimized for hybrid analytical and vector queries.' },
  'milvus': { front: 'Milvus', back: 'Purpose-built vector database for billion-scale workloads. Separates compute and storage; needs Kubernetes.' },
  'pgvector': { front: 'pgvector', back: 'A Postgres extension that adds a vector data type with HNSW and IVFFlat indexes. "Use the database you already have."' },
  'hnsw': { front: 'HNSW', back: 'Hierarchical Navigable Small World. Graph-based ANN algorithm; the dominant default for vector search. Best recall-latency tradeoff.' },
  'ann': { front: 'ANN', back: 'Approximate Nearest Neighbor search. Trades small recall loss (typically <2%) for 100-1000x speedup over exact search.' },
  'ivf': { front: 'IVF', back: 'Inverted File index. ANN algorithm that partitions vectors into clusters; searches only clusters closest to the query.' },
  'ivf-pq': { front: 'IVF-PQ', back: 'IVF combined with Product Quantization. Compresses each vector into a few bytes; enables billion-scale indexes in modest memory.' },
  'diskann': { front: 'DiskANN', back: 'Graph-based ANN designed for SSD-backed indexes. Trades latency for ability to handle billion-scale vectors without keeping full index in RAM.' },
  'hybrid-search': { front: 'Hybrid search', back: 'Combining vector (semantic) and lexical (BM25) retrieval. Catches both kinds of relevance: paraphrase and exact-match.' },
  'rrf': { front: 'RRF', back: 'Reciprocal Rank Fusion. Combines multiple ranked lists by summing 1/(k+rank). The standard fusion algorithm for hybrid search.' },
  'reranking': { front: 'Reranking', back: 'Second-stage retrieval that scores (query, doc) pairs more carefully (typically cross-encoder). Lifts precision after broad first-stage retrieval.' },
  'bm25': { front: 'BM25', back: 'Lexical retrieval algorithm. Pre-LLM IR baseline; still essential as the lexical leg of hybrid search. Strong on exact-match terms.' },
  'cross-encoder': { front: 'Cross-encoder', back: 'Model that takes (query, document) pair as joint input and outputs a relevance score. Higher quality than vector similarity; slower; used for reranking.' },
  'bi-encoder': { front: 'Bi-encoder', back: 'Model that encodes queries and documents independently. Architecture behind almost all embedding models; cheap to run; lower-precision than cross-encoder.' },
  'query-expansion-rewriting': { front: 'Query expansion / rewriting', back: 'Generating multiple variant queries from a single user query before retrieval. Improves recall on under-specified or ambiguous queries.' },
  'hyde': { front: 'HyDE', back: 'Hypothetical Document Embeddings. Use the LLM to generate a hypothetical answer; embed that; use as the retrieval query.' },

  // ===== Module 4: Agents & MCP =====
  'ai-agent': { front: 'AI agent', back: 'A system that uses an LLM to reason, take actions via tools, observe results, and iterate toward a goal.' },
  'agent-vs-workflow-distinction': { front: 'Agent vs workflow', back: 'Agent: model decides next step. Workflow: developer hard-codes the steps. Most production "agents" are actually workflows with model-flavored steps.' },
  'agentic-loop': { front: 'Agentic loop', back: 'Plan -> act (call tool) -> observe -> reflect -> repeat. The core control structure of an agent.' },
  'tool-use': { front: 'Tool use (function calling)', back: 'Model produces a structured tool-call instead of free text. Runtime executes the tool and returns the result for the model to continue.' },
  'tool-definition-schema': { front: 'Tool definition / schema', back: 'JSON description of a tool: name, purpose, parameters, return type. The contract the model uses to decide whether and how to call the tool.' },
  'multi-agent-system': { front: 'Multi-agent system', back: 'Multiple specialized agents collaborating, often with one orchestrator delegating to specialists. Powerful when tasks are clearly separable; otherwise overhead.' },
  'agent-orchestration': { front: 'Agent orchestration', back: 'Coordinating multiple agents or steps. Sequential, parallel, conditional, iterative. LangGraph, Mastra, Temporal-style durable execution.' },
  'handoff-delegation': { front: 'Handoff / delegation', back: 'Passing control from one agent to another with a defined context bundle. Atomic primitive of multi-agent systems; OpenAI Agents SDK formalized.' },
  'mcp': { front: 'MCP', back: 'Model Context Protocol. Anthropic\'s 2024 open standard for connecting models to tools and data sources. The "USB-C of AI integrations".' },
  'mcp-server': { front: 'MCP server', back: 'Process exposing tools, resources, and prompts via the MCP protocol. Run locally (stdio) or remotely (SSE / HTTP).' },
  'mcp-client': { front: 'MCP client', back: 'Process connecting to MCP servers. Claude Desktop, Cursor, custom agents. Discovers tools, routes calls, returns results to the model.' },
  'mcp-transport': { front: 'MCP transport', back: 'How MCP messages travel: stdio (local subprocess), SSE (streaming HTTP), HTTP (request-response).' },
  'mcp-resource': { front: 'MCP resource', back: 'A piece of context (file, document, DB row) an MCP server exposes. Read by the client, not invoked by the model directly.' },
  'mcp-prompt': { front: 'MCP prompt', back: 'A reusable prompt template an MCP server exposes. Lets server authors ship pre-engineered prompts the client can render.' },
  'subagent': { front: 'Subagent', back: 'Delegated agent invoked by a lead agent for a specific task. Runs in its own context window; returns a summary; keeps the lead\'s context clean.' },
  'langchain': { front: 'LangChain', back: 'Original LLM-app framework. Broad scope, deep ecosystem, sometimes accused of over-abstraction. Most-used Python LLM library in 2026.' },
  'langgraph': { front: 'LangGraph', back: 'Graph-based orchestration layer for agents and stateful workflows. The 2026 production-recommended path within LangChain stack.' },
  'llamaindex': { front: 'LlamaIndex', back: 'Framework focused on data ingestion and retrieval; increasingly agentic. Strongest opinionated stack for production RAG.' },
  'crewai': { front: 'CrewAI', back: 'Role-based agent framework. Fast scaffolding for multi-agent flows; opinionated about agent personas and task delegation.' },
  'pydantic-ai': { front: 'Pydantic AI', back: 'Type-safe agent framework built on Pydantic. Rapidly gaining adoption; preferred new-codebase choice for type-conscious Python teams.' },
  'mastra': { front: 'Mastra', back: 'TypeScript-first agent framework. Vercel-aligned; deployable to Vercel and Cloudflare Workers. 2026 default for Node-stack agent work.' },
  'claude-agent-sdk': { front: 'Claude Agent SDK', back: 'Anthropic\'s official agent-building toolkit. Wraps Claude Code\'s primitives (subagents, hooks, skills, MCP) as a programmable SDK.' },
  'openai-agents-sdk': { front: 'OpenAI Agents SDK', back: 'OpenAI\'s 2025 replacement for Swarm. Handoff-based architecture; production-grade.' },
  'google-adk': { front: 'Google ADK', back: 'Google\'s Agent Development Kit. Vertex AI-aligned framework for building agents on Gemini.' },
  'microsoft-agent-framework': { front: 'Microsoft Agent Framework', back: 'Microsoft\'s evolved agent framework. Successor to AutoGen; deep Microsoft Graph and Azure integration.' },
  'smolagents': { front: 'Smolagents', back: 'Hugging Face\'s minimal code-driven agent framework. Agents that write Python code rather than calling structured tools.' },
  'durable-execution': { front: 'Durable execution', back: 'Workflow pattern (Temporal, Inngest) for long-running agents that survive crashes. State persists; resumes from last checkpoint after failure.' },

  // ===== Module 5: The Anthropic Stack =====
  'agent-development-kit': { front: 'Agent Development Kit', back: 'Anthropic\'s 5-layer system: Memory (CLAUDE.md), Knowledge (Skills), Guardrails (Hooks), Delegation (Subagents), Distribution (Plugins).' },
  'claude-md': { front: 'CLAUDE.md', back: 'Memory layer of Anthropic ADK. Persistent instructions Claude reads on every session. Lives globally (~/.claude/) or per-project (.claude/CLAUDE.md).' },
  'claude-skills': { front: 'Claude Skills', back: 'Knowledge layer of Anthropic ADK. Reusable workflows triggered by context. Progressive disclosure: only the relevant skill loads per task.' },
  'skill-md': { front: 'SKILL.md', back: 'File format defining a Claude Skill: name, description (with positive AND negative triggers), instructions, optional helper scripts.' },
  'progressive-disclosure': { front: 'Progressive disclosure', back: 'Skills load only when their description matches context. Avoids context bloat; only the relevant capability surfaces per task.' },
  'skill-design-pattern-generator': { front: 'Skill: Generator pattern', back: 'Skill that produces an artifact from static knowledge. No questions asked; "given X, write Y" workflow.' },
  'skill-design-pattern-inversion': { front: 'Skill: Inversion pattern', back: 'Skill that asks the user questions before executing. "Tell me X, Y, Z; then I produce the artifact." Best for full-stack feature builds.' },
  'skill-design-pattern-chained-inversion': { front: 'Skill: Chained Inversion', back: 'Skill that sequentially asks questions, performs intermediate actions, chains results. Multi-turn interview-driven workflows.' },
  'skill-creator': { front: 'skill-creator', back: 'Anthropic\'s meta-skill that interviews you about a workflow, then writes a SKILL.md and supporting files for it.' },
  'hooks': { front: 'Hooks', back: 'Guardrail layer of Anthropic ADK. Scripts that fire on events (PreToolUse, PostToolUse, SessionStart, Stop) and can approve, block, or modify actions.' },
  'pretooluse-posttooluse-sessionstart-stop-subagentstop': { front: 'Hook event types', back: 'PreToolUse (before tool call), PostToolUse (after), SessionStart, Stop, SubagentStop. Each is a hook point for scripts.' },
  'subagents': { front: 'Subagents (ADK layer)', back: 'Delegation layer of Anthropic ADK. Specialized agents the lead agent invokes for specific tasks. Independent context; clean handoffs.' },
  'plugins': { front: 'Plugins', back: 'Distribution layer of Anthropic ADK. Bundle Skills, Hooks, Subagents, MCP servers as one installable artifact.' },
  'plugin-marketplace': { front: 'Plugin marketplace', back: 'Discoverable store for Claude plugins. One-click install per repo. Distribution layer of the ADK.' },
  'cowork': { front: 'Cowork', back: 'Anthropic\'s collaborative agentic workspace where Skills and skill-creator live. Chat-plus-canvas interface for non-coding agentic tasks.' },
  'claude-in-excel': { front: 'Claude in Excel', back: 'Anthropic\'s spreadsheet-native Claude integration. =CLAUDE() in-cell formulas; side-panel chat. Bulk classification, extraction, rewrite over rows.' },
  'claude-in-chrome': { front: 'Claude in Chrome', back: 'Anthropic\'s browser-resident Claude integration. Side panel + per-tab agent that can read DOM, navigate, and take actions on web pages.' },
  'claude-desktop': { front: 'Claude Desktop', back: 'Native macOS / Windows Claude app. Default surface for chat-style interaction with MCP integrations.' },
  'claude-code': { front: 'Claude Code', back: 'Anthropic\'s terminal-resident, code-focused agent. Built on the ADK primitives. The reference agentic coding tool in 2026.' },
  'anthropic-api': { front: 'Anthropic API', back: 'Programmatic interface to Claude. /messages (chat), /messages/batches (async batch), /tokens/count. Foundation every Anthropic surface is built on.' },
  'prompt-caching-anthropic': { front: 'Prompt caching (Anthropic)', back: 'Marks portions of the prompt as cacheable; reads cost ~10% of normal token price. 5-minute TTL; extended-cache for stable prefixes.' },
  'batch-api-anthropic': { front: 'Batch API (Anthropic)', back: 'Asynchronous batch endpoint at 50% discount. Up to 100K requests; results within 24 hours.' },
  'computer-use': { front: 'Computer use', back: 'Anthropic\'s capability for Claude to control a virtual computer via screenshots and keyboard / mouse. Sandbox required for safety.' },
  'extended-thinking': { front: 'Extended thinking', back: 'Anthropic\'s feature exposing Claude\'s chain-of-thought reasoning. Configurable thinking budget per request; billed at output rate.' },
  'constitutional-ai': { front: 'Constitutional AI', back: 'Anthropic\'s training methodology. Model learns to align with a written constitution of principles via critic-model feedback.' },
  'claude-opus-sonnet-haiku': { front: 'Opus / Sonnet / Haiku', back: 'Anthropic model tiers. Opus: largest, deepest reasoning. Sonnet: balanced workhorse. Haiku: fastest, cheapest. Same training family.' },

  // ===== Module 6: Voice & Multimodal =====
  'multimodal-model': { front: 'Multimodal model', back: 'Model accepting and/or producing multiple modalities (text, image, audio, video). Standard for frontier models in 2026.' },
  'vision-language-model-vlm': { front: 'VLM', back: 'Vision-Language Model. Processes both images and text. The "vision" leg of multimodal; standard in frontier 2026 models.' },
  'text-to-speech-tts': { front: 'TTS', back: 'Text-to-Speech. Generating natural speech audio from text input. Output side of voice agents.' },
  'speech-to-text-stt': { front: 'STT (ASR)', back: 'Speech-to-Text / Automatic Speech Recognition. Transcribing audio to text. Input side of voice agents.' },
  'whisper': { front: 'Whisper', back: 'OpenAI\'s open-source ASR model. The de facto STT standard since 2022; multiple variants (faster-whisper, distil-whisper, WhisperX).' },
  'realtime-api': { front: 'Realtime API', back: 'OpenAI\'s low-latency speech-to-speech API. Audio in / audio out without explicit STT/TTS steps; sub-500ms round-trip.' },
  'elevenlabs': { front: 'ElevenLabs', back: 'Leading commercial TTS provider. Known for voice cloning, emotion control, multilingual coverage. Quality-first.' },
  'cartesia': { front: 'Cartesia', back: 'TTS provider focused on ultra-low latency for voice agents. Sub-100ms time-to-first-audio. Latency-first.' },
  'deepgram': { front: 'Deepgram', back: 'STT provider with strongest streaming-mode latency profile. Sub-200ms streaming transcription. Default 2026 voice-agent choice.' },
  'voice-agent-architecture': { front: 'Voice agent architecture', back: 'VAD -> STT -> LLM -> TTS -> audio out. Latency budget ~800ms round-trip; achievable in ~500ms with tight pipeline.' },
  'vad': { front: 'VAD', back: 'Voice Activity Detection. Identifies when the user has stopped speaking so the agent can respond. First stage of any voice agent.' },
  'streaming-inference': { front: 'Streaming inference', back: 'Returning model output token-by-token as it generates. The reason chat feels responsive on long generations.' },
  'image-generation-models': { front: 'Image generation models', back: 'Diffusion-based: Imagen 4, DALL-E 4, Flux, Stable Diffusion 4, Midjourney v7. Generate images from text prompts.' },
  'video-generation': { front: 'Video generation', back: 'Text-to-video and image-to-video. 2026: Sora 2, Veo 3, Runway Gen-4, Kling 2.5. Approaching but not matching cinema-quality production.' },

  // ===== Module 7: Local-First AI & Personal Knowledge Stacks =====
  'local-first-ai': { front: 'Local-first AI', back: 'Running models on your own hardware for privacy, sovereignty, cost predictability, capability ownership.' },
  'the-capability-ceiling': { front: 'The capability ceiling', back: 'Cloud frontier still beats any 70B local model on hardest tasks (coding agents, complex reasoning). Local works for most personal tasks; not all.' },
  'the-case-for-local': { front: 'Case for local AI', back: 'Privacy (NDA / regulated data), no rate limits, no token costs at heavy use, sovereignty, learning by running.' },
  'the-case-against-local': { front: 'Case against local AI', back: 'Capability ceiling, maintenance overhead, hardware cost, electricity, time cost of becoming a sysadmin instead of a builder.' },
  'the-hybrid-stack-pattern': { front: 'Hybrid stack pattern', back: 'Local for personal / sensitive work, cloud frontier for hard reasoning, gateway in between routing requests. Dominant 2026 pattern.' },
  'apple-silicon-unified-memory-architecture': { front: 'Apple Silicon unified memory', back: 'CPU and GPU share the same memory pool. Lets you load 100B+ models that would not fit in any consumer GPU\'s VRAM.' },
  'memory-bandwidth': { front: 'Memory bandwidth', back: 'Often more important than VRAM size for inference throughput. M3 Ultra: 819GB/s. RTX 4090: 1008GB/s.' },
  'vram-vs-unified-memory-tradeoff': { front: 'VRAM vs unified memory', back: 'Dedicated VRAM: faster per-byte, capped low. Unified memory: slower per-byte, lets you fit bigger models.' },
  'mac-studio-m3-ultra-512gb': { front: 'Mac Studio M3 Ultra 512GB', back: '2026\'s reference local AI workstation. ~$12K configured; runs 100B+ models with MLX.' },
  'mac-mini-m4-pro': { front: 'Mac Mini M4 Pro', back: 'Entry-point local AI machine. 64GB ceiling; ~$2K-3K. Runs 7B-30B models comfortably.' },
  'nvidia-rtx-5090': { front: 'NVIDIA RTX 5090', back: 'Released late 2025; 32GB VRAM, ~1700GB/s bandwidth. Consumer GPU choice for local serving in 2026.' },
  'nvidia-rtx-4090': { front: 'NVIDIA RTX 4090', back: '24GB VRAM; 1008GB/s bandwidth. Previous-generation workhorse still common in personal rigs.' },
  'multi-gpu-rigs': { front: 'Multi-GPU rigs', back: '2x or 4x 4090, dual H100. Path beyond what a single Mac or single GPU can hold. Tensor / pipeline / expert parallelism splits the model.' },
  'threadripper-epyc-for-hosting': { front: 'Threadripper / EPYC', back: 'High-core-count AMD CPUs paired with multi-GPU. Threadripper Pro has 128 PCIe lanes; consumer CPUs have 24-28.' },
  'nvidia-project-digits': { front: 'NVIDIA Project DIGITS', back: 'Personal AI computer announced CES 2025. ~$3K, 128GB unified memory; runs 200B-class models.' },
  'framework-desktop-with-amd-ryzen-ai-max-395': { front: 'Framework Desktop (AMD AI Max+)', back: '2026 release. 128GB unified memory in small form factor. AMD\'s answer to Mac Studio for local AI.' },
  'tinybox-tinygrad': { front: 'TinyBox / tinygrad', back: 'George Hotz\'s pre-built multi-GPU AI workstations and their underlying minimal ML framework.' },
  'gguf': { front: 'GGUF', back: 'llama.cpp\'s native quantized model format. Widely supported; runs on CPU, Apple Metal, CUDA. Most-used local format in 2026.' },
  'awq': { front: 'AWQ', back: 'Activation-aware Weight Quantization. Efficient INT4 preserving important weight magnitudes. Popular for serving.' },
  'gptq': { front: 'GPTQ', back: 'Older post-training quantization. Largely superseded by AWQ for INT4 in 2026.' },
  'mlx': { front: 'MLX', back: 'Apple\'s quantization format and inference framework optimized for Apple Silicon. NumPy-like API; native unified-memory support.' },
  'exl2': { front: 'EXL2', back: 'Quantization format popular for serving on consumer NVIDIA GPUs. Mixed-precision; good quality at low bit-widths.' },
  'hqq': { front: 'HQQ', back: 'Half-Quadratic Quantization. Strong quality at low bit-width; faster to compute than GPTQ.' },
  'fp16-bf16-fp8-mixed-precision': { front: 'FP16 / BF16 / FP8', back: 'Reduced-precision floating-point formats. FP8 is the new datacenter standard; supported on H100 and B200.' },
  'int8-vs-int4-tradeoffs': { front: 'INT8 vs INT4', back: 'INT8: near-lossless. INT4: 2x more memory savings at noticeable quality cost. Run an eval to confirm tradeoff for your task.' },
  'activation-vs-weight-quantization': { front: 'Activation vs weight quantization', back: 'Quantizing static weights is easier; quantizing dynamic activations enables more compression but is harder.' },
  'ollama': { front: 'Ollama', back: 'De facto local model server. CLI-first; REST API at localhost:11434. Default 2026 entry point for local AI.' },
  'lm-studio': { front: 'LM Studio', back: 'GUI-first local model runner. Polished desktop application; OpenAI-compatible API endpoint.' },
  'jan': { front: 'Jan', back: 'Apache 2.0 open-source ChatGPT alternative. No telemetry; privacy-focused desktop app.' },
  'gpt4all': { front: 'GPT4All', back: 'Cross-platform local LLM runner from Nomic. Built-in document Q-A; mature UI.' },
  'llama-cpp': { front: 'llama.cpp', back: 'C++ inference engine powering most local LLM tools. Introduced GGUF; foundational layer of the local AI stack.' },
  'vllm': { front: 'vLLM', back: 'Production inference server with continuous batching. Default for serving open-weight at scale; 5-30x throughput over naive serving.' },
  'sglang': { front: 'SGLang', back: 'High-throughput inference engine with RadixAttention. Deployed on 400K+ GPUs. Strong fit for agent workloads with shared prefixes.' },
  'tensorrt-llm': { front: 'TensorRT-LLM', back: 'NVIDIA\'s optimized inference. Best raw H100 / B200 performance; NVIDIA-locked.' },
  'hugging-face-tgi': { front: 'Hugging Face TGI', back: 'Entered maintenance mode Dec 2025; HF recommends migration to vLLM or SGLang for new deployments.' },
  'mistral-rs': { front: 'mistral.rs', back: 'Rust-based inference server. Gaining traction in 2026 for memory safety and concurrency.' },
  'llamafile': { front: 'llamafile', back: 'Mozilla\'s single-file deployable model. Bundles model + runtime into one cross-platform executable.' },
  'koboldcpp': { front: 'KoboldCpp', back: 'Local serving frontend popular for creative writing and roleplay. Long-context generation, character cards.' },
  'text-generation-webui': { front: 'text-generation-webui', back: 'Veteran web UI for local LLMs (oobabooga). Supports many backends; heavy customization; many extensions.' },
  'localai': { front: 'LocalAI', back: 'Open-source drop-in replacement for the OpenAI API, served from local models. Existing OpenAI code works with a base URL change.' },
  'continuous-batching': { front: 'Continuous batching', back: 'vLLM\'s core innovation. Process multiple requests at varying generation stages simultaneously. 5-15x throughput gain.' },
  'pagedattention': { front: 'PagedAttention', back: 'vLLM\'s memory management technique. Borrowed from OS virtual memory; allocates KV cache in fixed-size pages.' },
  'radixattention': { front: 'RadixAttention', back: 'Sharing KV cache across requests with common prefixes. SGLang\'s differentiating innovation; dramatic throughput on agent workloads.' },
  'tensor-pipeline-expert-parallelism': { front: 'Parallelism types', back: 'Tensor: split each layer across GPUs. Pipeline: split layers across GPUs. Expert: for MoE, split experts across GPUs.' },
  'llama-family': { front: 'Llama family', back: 'Meta\'s open-weight models (Llama 3.x, 4). Most-deployed open base in 2026. Commercial-friendly license with restrictions for very large platforms.' },
  'mistral-family': { front: 'Mistral family', back: 'Mistral AI\'s open-weight (Mistral 7B, Mixtral, Mistral Large). Apache 2.0; strong on European languages.' },
  'qwen-family': { front: 'Qwen family', back: 'Alibaba\'s open-weight (Qwen 2.5, Qwen 3). Strong multilingual and reasoning. Apache 2.0.' },
  'deepseek-family': { front: 'DeepSeek family', back: 'DeepSeek\'s open-weight including R1 reasoning models. MIT licensed; the most permissive among major open-weight.' },
  'gemma-family': { front: 'Gemma family', back: 'Google\'s open-weight derived from Gemini methodology. Strong on smaller-scale deployments. Custom commercial-friendly license.' },
  'granite-family': { front: 'Granite family', back: 'IBM\'s open-weight (Granite 3.x, Granite Code). Apache 2.0; aimed at enterprise and code use cases.' },
  'phi-family': { front: 'Phi family', back: 'Microsoft\'s open-weight small models. Strong quality per parameter; aimed at smaller and edge deployments.' },
  'command-r-family': { front: 'Command R family', back: 'Cohere\'s open-weight. Optimized for RAG and tool use. CC-BY-NC for non-commercial; requires Cohere licensing for commercial.' },
  'capture-layer': { front: 'Capture layer', back: 'First layer of personal knowledge stack. Frictionless input: Apple Notes, Drafts, voice memos. Capture must be fast enough not to lose the thought.' },
  'vault-layer': { front: 'Vault layer', back: 'Second layer of personal knowledge stack. Long-term knowledge graph: Obsidian, Logseq, Notion. Markdown-based vaults outlive the tool.' },
  'local-model-layer': { front: 'Local model layer', back: 'Third layer of personal knowledge stack. Where local AI lives: Ollama, LM Studio. Pairs with vault via retrieval.' },
  'local-retrieval-rag-layer': { front: 'Local retrieval / RAG layer', back: 'Fourth layer of personal knowledge stack. AnythingLLM, Khoj, Onyx, Smart Connections. Personal RAG over your data.' },
  'agent-automation-layer': { front: 'Agent automation layer', back: 'Fifth layer of personal knowledge stack. Local automations and agents: Raycast scripts, Hammerspoon, Keyboard Maestro.' },
  'orchestration-front-end-layer': { front: 'Orchestration / front-end layer', back: 'Sixth layer of personal knowledge stack. Open WebUI, LibreChat, LobeChat. Interaction surface for the local AI stack.' },
  'memory-layer': { front: 'Memory layer', back: 'Seventh layer of personal knowledge stack. Persistent memory across agent sessions: Mem0, Zep, Letta, Cognee.' },
  'capture-to-knowledge-pipelines': { front: 'Capture-to-knowledge pipelines', back: 'End-to-end pipelines from raw capture to organized knowledge. Voice memo -> Whisper -> classification -> Obsidian -> embedding -> retrieval.' },
  'apple-notes': { front: 'Apple Notes', back: 'Apple\'s default notes app. Frictionless capture across iOS and macOS; less suited for long-term knowledge organization.' },
  'drafts': { front: 'Drafts', back: 'Mac and iOS text-first capture app. Opens to a blank input; downstream actions are scriptable.' },
  'google-keep': { front: 'Google Keep', back: 'Google\'s lightweight note-taking app. Cross-platform; minimal but reliable capture in the Google ecosystem.' },
  'bear': { front: 'Bear', back: 'Mac and iOS notes app with Markdown support. Polished UX between Apple Notes and Obsidian.' },
  'day-one': { front: 'Day One', back: 'Journaling-focused app. Date-driven; rich entries with photos, location, weather. Encrypted long-term storage.' },
  'reflect': { front: 'Reflect', back: 'Note-taking app with built-in AI features. Cross-device sync; AI search and summarization integrated.' },
  'mem-ai': { front: 'Mem.ai', back: 'AI-native notes app. Auto-organizes captures via AI-generated tags and summaries; capture is friction-free.' },
  'obsidian': { front: 'Obsidian', back: 'Markdown-based vault. 2026 default for power-user PKM. Local files; bidirectional links; large plugin ecosystem.' },
  'logseq': { front: 'Logseq', back: 'Outliner-based vault. Daily-notes-first; bullet hierarchy as primary structure. Markdown / Org-mode.' },
  'notion': { front: 'Notion', back: 'Cloud-based workspace. Database-driven; team-friendly. Less local-first than Obsidian; export-to-Markdown is functional but lossy.' },
  'roam-research': { front: 'Roam Research', back: 'Bidirectional-link pioneer (2019-2020). Cloud-hosted with local export. Less popular in 2026 vs Obsidian / Logseq.' },
  'capacities': { front: 'Capacities', back: 'Object-based PKM. Notes as typed objects (book, person, project) with structured relationships.' },
  'tana': { front: 'Tana', back: 'Block-based with supertags. Outliner UX plus structured queryable supertags. Growing in 2026.' },
  'anytype': { front: 'Anytype', back: 'Decentralized, end-to-end encrypted. Object-based data model similar to Notion but local-first and peer-to-peer.' },
  'standard-notes': { front: 'Standard Notes', back: 'End-to-end encrypted notes. Security-focused; minimal feature set by design.' },
  'heptabase': { front: 'Heptabase', back: 'Visual canvas-based PKM. Whiteboard-first; spatial arrangement and explicit links. Strong fit for visual thinkers.' },
  'joplin': { front: 'Joplin', back: 'Open-source notes alternative. Sync flexibility (local, Dropbox, Nextcloud, OneDrive). Self-hosted-friendly.' },
  'para': { front: 'PARA', back: 'Tiago Forte\'s organizational scheme: Projects, Areas, Resources, Archive. Notes flow between buckets as priorities shift.' },
  'code': { front: 'CODE', back: 'Tiago Forte\'s process scheme: Capture, Organize, Distill, Express. The lifecycle of a note across multiple revisits.' },
  'basb': { front: 'BASB', back: 'Building a Second Brain. Forte\'s full method (PARA + CODE) formalized in the 2022 book.' },
  'zettelkasten': { front: 'Zettelkasten', back: 'Niklas Luhmann\'s atomic, networked note method. Bidirectional links and unique IDs predate digital tools.' },
  'smart-notes': { front: 'Smart Notes', back: 'Sönke Ahrens\'s 2017 adaptation of Zettelkasten for the digital age. Practical step-by-step.' },
  'atomic-notes': { front: 'Atomic notes', back: 'Each note expresses one idea, fully self-contained. The atomicity principle; enables linking and recombination.' },
  'evergreen-notes': { front: 'Evergreen notes', back: 'Andy Matuschak\'s term for notes refined over time. Atomic, concept-oriented, density grows with revisits.' },
  'bidirectional-links': { front: 'Bidirectional links', back: 'Links that automatically create backlinks. Network effect of a vault: graph grows in both directions from a single edit.' },
  'backlinks': { front: 'Backlinks', back: 'Auto-generated reverse references showing what links to the current note. Surfaces context that explicit search would miss.' },
  'daily-notes': { front: 'Daily notes', back: 'One note per day as primary capture surface. Pre-populated date and template; popular in Logseq, Roam, Obsidian.' },
  'markdown-as-universal-format': { front: 'Markdown as universal format', back: 'Plain text that survives any tool change. The portability principle; choose Markdown-based tools for long-term knowledge.' },
  'obsidian-sync': { front: 'Obsidian Sync', back: 'First-party encrypted sync service. ~$4-5/mo; end-to-end encrypted across Obsidian installations.' },
  'obsidian-publish': { front: 'Obsidian Publish', back: 'First-party publishing of vault contents to the web. ~$8-10/mo per site; bidirectional links preserved.' },
  'smart-connections-plugin': { front: 'Smart Connections', back: 'Obsidian plugin for RAG over your vault using local or cloud embeddings. Brings AI search inside the vault.' },
  'copilot-for-obsidian': { front: 'Copilot for Obsidian', back: 'Plugin bringing LLM chat into Obsidian with vault-aware context. Configurable to OpenAI, Claude, Ollama.' },
  'templater-plugin': { front: 'Templater plugin', back: 'Obsidian plugin: programmable templates with JavaScript execution. Power tool for vault automation.' },
  'dataview-plugin': { front: 'Dataview plugin', back: 'Obsidian plugin: treat your vault as a database. Query notes by metadata with SQL-like or DQL syntax.' },
  'bases': { front: 'Bases', back: 'Native Obsidian database views (shipped 2026 in v1.5+). Tables, kanban, calendar over typed properties.' },
  'excalidraw-plugin': { front: 'Excalidraw plugin', back: 'Obsidian plugin: visual diagramming with hand-drawn aesthetic. Embeddable in notes.' },
  'canvas': { front: 'Canvas', back: 'Native Obsidian whiteboard. Infinite surface; drag notes spatially; embedded notes remain live.' },
  'anythingllm': { front: 'AnythingLLM', back: 'Workspace-based local RAG with no-code agent builder. 53K+ stars; polished UI for personal/team use.' },
  'open-webui': { front: 'Open WebUI', back: 'Most-popular self-hosted ChatGPT alternative. 124K+ stars. Polished chat against any OpenAI-compatible endpoint.' },
  'khoj': { front: 'Khoj', back: 'Multi-platform personal AI. Obsidian, Emacs, browser, mobile, WhatsApp. Self-hostable; cross-surface access.' },
  'onyx': { front: 'Onyx', back: 'Self-hosted enterprise-style RAG (formerly Danswer). 40+ connectors: GitHub, Confluence, Slack, Notion, Drive.' },
  'librechat': { front: 'LibreChat', back: 'Privacy-focused multi-provider chat unifier. One interface against multiple AI providers; self-hostable.' },
  'lobechat': { front: 'LobeChat', back: 'Multi-agent chat with Agent Groups and 10K+ MCP skills. Power-user chat with agentic capabilities.' },
  'mem0': { front: 'Mem0', back: 'Framework-agnostic memory layer. Drop-in for LangChain, CrewAI, AutoGen. 48K+ stars.' },
  'zep': { front: 'Zep', back: 'Production-grade hybrid vector + graph memory. Graphiti for temporal facts. Self-hosted or hosted SaaS.' },
  'cognee': { front: 'Cognee', back: 'Deep knowledge retrieval over graph + vector representations. Builds knowledge graphs from documents for richer recall.' },
  'langchain-memory': { front: 'LangChain Memory', back: 'LangChain\'s first-party memory abstractions. ConversationBufferMemory, ConversationSummaryMemory, VectorStoreRetrieverMemory.' },
  'llamaindex-memory': { front: 'LlamaIndex Memory', back: 'LlamaIndex\'s first-party memory abstractions. Integrated with retrieval and agent layers.' },
  'letta': { front: 'Letta', back: 'Agent runtime with OS-style tiered memory: Core (in-context), Recall (searchable), Archival (cold storage). Formerly MemGPT.' },
  'granola': { front: 'Granola', back: 'AI-native meeting notes app. Records, transcribes, produces structured notes (TL;DR, decisions, action items) automatically.' },
  'otter-ai': { front: 'Otter.ai', back: 'Veteran transcription and meeting notes service. Long history (since 2016); broad enterprise adoption.' },
  'fireflies': { front: 'Fireflies', back: 'AI meeting recorder with searchable transcripts. Strong on the transcript-search use case.' },
  'limitless': { front: 'Limitless', back: 'Always-on capture device + app (formerly Rewind). Continuous recording for searchable lifelog.' },
  'personal-ai': { front: 'Personal.ai', back: 'Personal AI model fine-tuned on your captured data. AI that speaks "in your voice" and recalls your context.' },
  'whisper-cpp': { front: 'whisper.cpp', back: 'C++ port of OpenAI Whisper for local transcription. CPU-friendly; GPU acceleration via Metal or CUDA.' },
  'whisperx': { front: 'WhisperX', back: 'Faster Whisper with word-level timestamps and optional speaker diarization.' },
  'vosk': { front: 'Vosk', back: 'Offline ASR engine. Smaller than Whisper but faster on commodity hardware. 20+ languages.' },
  'piper': { front: 'Piper', back: 'Local TTS. Fast, lightweight neural TTS that runs on Raspberry Pi and modest CPUs.' },
  'bark': { front: 'Bark', back: 'Open-source generative TTS with voice presets. Suno research; speech, music, sound effects from text.' },
  'melotts': { front: 'MeloTTS', back: 'Multilingual local TTS. Strong on multiple languages from a single model.' },
  'r-localllama': { front: 'r/LocalLLaMA', back: 'Canonical Reddit community for local LLM hardware, quantization, serving. Hub for the local-AI movement.' },
  'hugging-face-spaces': { front: 'Hugging Face Spaces', back: 'Public model deployment showcase. Try community models in seconds via free Gradio or Streamlit UI.' },
  'ollama-community': { front: 'Ollama community', back: 'Discord and Reddit hubs for Ollama-specific patterns. Active support community for the dominant local model server.' },

  // ===== Module 8: Evals & Observability =====
  'evaluation-eval': { front: 'Evaluation (eval)', back: 'Systematic measurement of model output quality. The discipline that separates "it worked once" from "it works in production".' },
  'golden-set': { front: 'Golden set', back: 'Curated set of test cases with known-correct outputs. The reference benchmark you measure against. Pull from real production traces.' },
  'llm-as-judge': { front: 'LLM-as-judge', back: 'Using a (usually larger) LLM to score outputs against a rubric. Captures subjective quality (helpfulness, faithfulness) that rigid metrics miss.' },
  'aligning-llm-as-judge-to-human-judgment': { front: 'Aligning LLM-as-judge', back: 'Calibrating the judge model\'s scores against human ratings on a sample. Without alignment, judge scores correlate with what the judge cares about, not users.' },
  'ragas': { front: 'RAGAS', back: 'RAG Assessment framework. Standardized RAG metrics: faithfulness, answer relevancy, context precision, context recall. Pre-built scorers.' },
  'error-analysis-axial-coding': { front: 'Error analysis / axial coding', back: 'Read errors, categorize into emergent codes, prioritize fixes by frequency. Hamel Husain framing: read the failures before chasing metrics.' },
  'faithfulness': { front: 'Faithfulness', back: 'Whether the answer is grounded in retrieved context, not hallucinated. The single most important RAG quality metric.' },
  'answer-relevancy': { front: 'Answer relevancy', back: 'Whether the answer addresses the user\'s actual question. Distinct from faithfulness: relevancy is about question-answer fit.' },
  'context-precision-recall': { front: 'Context precision / recall', back: 'Precision: are retrieved chunks relevant? Recall: were all relevant chunks retrieved? Both matter; optimize the one your failure mode points to.' },
  'beir': { front: 'BEIR', back: 'Benchmark suite for retrieval evaluation across 18 domains. Standard reference for comparing retrieval models.' },
  'mteb': { front: 'MTEB', back: 'Massive Text Embedding Benchmark. The canonical 2026 leaderboard for embedding model evaluation across 50+ tasks.' },
  'promptfoo': { front: 'Promptfoo', back: 'Open-source CLI for prompt and RAG eval. Comparison-driven matrix; supports red-team mode.' },
  'langsmith': { front: 'LangSmith', back: 'LangChain\'s observability and eval platform. Tight integration with LangChain code; managed service.' },
  'langfuse': { front: 'Langfuse', back: 'Open-source LLM observability platform. Popular self-hosted choice; comparable feature set to LangSmith.' },
  'helicone': { front: 'Helicone', back: 'LLM observability via proxy. Sit between code and model API; gain logging and metrics with one URL change.' },
  'arize-phoenix': { front: 'Arize Phoenix', back: 'Open-source LLM observability with strong tracing. OpenTelemetry-native; built-in evaluators.' },
  'braintrust': { front: 'Braintrust', back: 'Eval-first LLM observability platform. Popular at AI-native vendors; CI gates on eval scores.' },
  'inspect': { front: 'Inspect', back: 'UK AI Safety Institute\'s eval framework. Rigorous, research-grade. Reference for safety and capability evaluations.' },
  'hallucination': { front: 'Hallucination', back: 'Model output that asserts false information confidently. Dominant LLM failure mode for trust-sensitive applications.' },
  'drift-detection': { front: 'Drift detection', back: 'Monitoring whether a model\'s behavior or input distribution is changing over time. Catches silent regressions after vendor model snapshot rotations.' },

  // ===== Module 9: Deployment, Ops, and Gateways =====
  'inference-serving': { front: 'Inference serving', back: 'Running models in production to handle live requests. GPU pool sizing, batching, autoscaling, observability, failover.' },
  'batch-api': { front: 'Batch API', back: 'Asynchronous batch endpoint at ~50% discount. Anthropic, OpenAI, Gemini all offer; up to 100K requests; 24-hour SLO.' },
  'streaming-responses': { front: 'Streaming responses', back: 'Returning tokens as they generate via SSE or chunked HTTP. Default UX pattern for chat-style interfaces.' },
  'rate-limiting': { front: 'Rate limiting', back: 'Caps on requests per second / minute / day imposed by vendors. Implement exponential backoff with jitter; per-user budgets; graceful fallback.' },
  'tpm-rpm': { front: 'TPM / RPM', back: 'Tokens per minute and requests per minute. The two axes most rate limits operate on. Calculate both for your traffic shape.' },
  'token-budgeting': { front: 'Token budgeting', back: 'Estimating and constraining token spend per user, session, or feature. Per-request, per-session, per-feature caps. Prevents runaway cost.' },
  'cost-estimation': { front: 'Cost estimation', back: 'Tokens-per-call x calls-per-user x users x price-per-token. Account for prompt caching (90% off cached portions) and batch (50% off).' },
  'model-gateway': { front: 'Model gateway', back: 'Middleware unifying multiple model APIs behind one interface. Adds caching, retry logic, fallback routing, observability.' },
  'litellm': { front: 'LiteLLM', back: 'Open-source unified interface to 100+ LLM APIs. Most-deployed gateway library in 2026 Python and Node stacks.' },
  'portkey': { front: 'Portkey', back: 'Commercial AI gateway with enterprise observability and governance. Virtual keys with separate budgets; SOC 2 / HIPAA-friendly.' },
  'openrouter': { front: 'OpenRouter', back: 'Hosted model marketplace with unified API. One account, one API key, access to 200+ models across vendors.' },
  'model-routing': { front: 'Model routing', back: 'Sending different requests to different models based on cost, latency, capability. 2-10x cost savings on most workloads.' },
  'fallback-strategy': { front: 'Fallback strategy', back: 'Automatically retrying failed requests on a backup model or vendor. Triggers: 429s, outages, latency, refusals.' },
  'logging-best-practices-for-llms': { front: 'LLM logging best practices', back: 'Capture prompts, responses, model version, user attribution, tool calls, latency, cost. Redact PII before persisting.' },
  'pii-redaction': { front: 'PII redaction', back: 'Removing personally identifiable info from prompts and logs. Required for regulated industries; sound for any production app.' },
  'microsoft-presidio': { front: 'Microsoft Presidio', back: 'Open-source PII detection and redaction library. Default 2026 self-hosted choice for compliance-conscious deployments.' },
  'agent-sandboxing': { front: 'Agent sandboxing', back: 'Isolating agent code execution to prevent damage from prompt injection or model errors. Containers, VMs, language-level sandboxes.' },
  'kubernetes-for-llm-serving': { front: 'Kubernetes for LLM serving', back: 'Container orchestration patterns for GPU workloads: dedicated node pools, autoscaling, KEDA-driven scaling on queue depth, taints for GPU isolation.' },

  // ===== Module 10: Fine-tuning & Post-training =====
  'fine-tuning': { front: 'Fine-tuning', back: 'Continuing training of a pre-trained model on task-specific data. Hardest path to capability gain; rarely the right first move.' },
  'full-fine-tuning': { front: 'Full fine-tuning', back: 'Updating all model parameters during training. Expensive in compute and memory; rarely used for production tuning in 2026.' },
  'peft': { front: 'PEFT', back: 'Parameter-Efficient Fine-Tuning. Methods updating only a small subset of parameters; LoRA dominates. Default 2026 fine-tuning approach.' },
  'lora': { front: 'LoRA', back: 'Low-Rank Adaptation. Adds small trainable matrices alongside frozen weights. Standard PEFT method.' },
  'qlora': { front: 'QLoRA', back: 'LoRA on a quantized base model. Lets you fine-tune 70B-class models on a single consumer GPU.' },
  'rlhf': { front: 'RLHF', back: 'Reinforcement Learning from Human Feedback. Train reward model from preferences; fine-tune LLM with RL to maximize reward.' },
  'dpo': { front: 'DPO', back: 'Direct Preference Optimization. Simpler alternative to RLHF; directly optimizes preference data without explicit reward model.' },
  'grpo': { front: 'GRPO', back: 'Group Relative Policy Optimization. DeepSeek\'s RL method that powered R1 reasoning models. Group-relative scoring.' },
  'raft': { front: 'RAFT', back: 'Retrieval-Augmented Fine-Tuning. Fine-tunes a model to better use retrieved context: cite sources, ignore distractors, fall back gracefully.' },
  'synthetic-data-generation': { front: 'Synthetic data generation', back: 'Using stronger models to generate training data for fine-tuning weaker models. Dominant 2026 dataset-creation approach.' },
  'catastrophic-forgetting': { front: 'Catastrophic forgetting', back: 'When fine-tuning erodes general capabilities the base model previously had. Hidden cost of aggressive task-specific training.' },
  'hugging-face-trl': { front: 'Hugging Face TRL', back: 'Open-source library for RLHF, DPO, post-training. Default 2026 toolkit for fine-tuning open-weight models.' },
  'axolotl': { front: 'Axolotl', back: 'Popular open-source fine-tuning framework with config-driven setup. YAML-driven CLI over TRL, Transformers, DeepSpeed.' },
  'unsloth': { front: 'Unsloth', back: 'Memory-optimized fine-tuning library. Significantly faster LoRA on consumer hardware via custom Triton kernels.' },

  // ===== Module 11: Enterprise Architecture & Governance =====
  'eu-ai-act': { front: 'EU AI Act', back: 'Comprehensive EU AI regulation. In force August 2024; full applicability for high-risk systems August 2 2026. Penalties up to 7% of global revenue.' },
  'eu-ai-act-risk-tiers': { front: 'EU AI Act risk tiers', back: 'Unacceptable (banned), high (heavy obligations), limited (transparency only), minimal (unregulated). Risk-based regulation.' },
  'gpai': { front: 'GPAI', back: 'General-Purpose AI models. Foundation models. Obligations live since August 2 2025; systemic-risk threshold at 10^25 FLOPs.' },
  'provider-deployer-importer-distributor': { front: 'EU AI Act roles', back: 'Provider (builds), Deployer (uses), Importer (places foreign systems on EU market), Distributor (makes available). Each has distinct obligations.' },
  'ai-literacy-obligation-art-4': { front: 'AI literacy (Article 4)', back: 'EU AI Act requirement for staff AI literacy proportional to role. Live since February 2 2025; documentation expected.' },
  'fria': { front: 'FRIA', back: 'Fundamental Rights Impact Assessment. Mandatory under EU AI Act for high-risk AI in public sector and certain private sectors.' },
  'nist-ai-rmf': { front: 'NIST AI RMF', back: 'US framework with four functions: GOVERN, MAP, MEASURE, MANAGE. Voluntary; de facto reference for most US federal contractors.' },
  'nist-ai-600-1': { front: 'NIST AI 600-1', back: 'NIST\'s GenAI-specific addendum. Catalogs 12 risk categories with 400+ mitigation actions.' },
  'iso-iec-42001': { front: 'ISO/IEC 42001', back: 'First certifiable AI management system standard. Modeled on ISO 27001 / 9001. AWS, Microsoft, Synthesia certified.' },
  'aims': { front: 'AIMS', back: 'AI Management System. Organization-wide system of policies, processes, controls. The thing ISO 42001 certifies.' },
  'iso-iec-23894-23053-22989-5338': { front: 'Companion ISO standards', back: '23894: AI risk. 23053: framework. 22989: terminology. 5338: lifecycle. Companions to ISO 42001.' },
  'colorado-ai-act-texas-traiga-nyc-ll-144-california-sb-53': { front: 'US state AI laws', back: 'Major US sub-federal AI laws as of 2026: Colorado AI Act, Texas TRAIGA, NYC LL 144 (bias audits), California SB 53 (frontier safety).' },
  'gdpr-article-22': { front: 'GDPR Article 22', back: 'EU right not to be subject to solely automated decisions producing legal or significant effects. Foundation for automated-decision regulation.' },
  'dpia': { front: 'DPIA', back: 'Data Protection Impact Assessment. GDPR-mandated risk assessment for high-risk personal data processing.' },
  'aiia': { front: 'AIIA', back: 'AI Impact Assessment. Generic AI risk assessment; combinable with DPIA and FRIA. Often the unified high-risk assessment.' },
  'sr-11-7': { front: 'SR 11-7', back: 'Federal Reserve / OCC supervisory letter on model risk management. Applied by most large US banks to AI / ML.' },
  'three-lines-of-defense': { front: 'Three lines of defense', back: 'Model owner (1st), independent validation (2nd), internal audit (3rd). Standard model-risk operating pattern.' },
  'model-inventory-and-tiering': { front: 'Model inventory + tiering', back: 'Cataloging all production models with criticality classification. Tier 1 gets full validation; tier 3 gets lighter controls.' },
  'model-card': { front: 'Model card', back: 'Standardized documentation of training, capabilities, limitations, intended use. Mitchell et al. 2019; now standard practice.' },
  'system-card': { front: 'System card', back: 'Vendor documentation of an AI system including evaluations, safety measures, known issues. Anthropic / OpenAI evolution of model card.' },
  'data-card': { front: 'Data card', back: 'Documentation of a dataset\'s provenance, composition, intended use. The data analog of the model card.' },
  'ai-bom': { front: 'AI BOM', back: 'AI Bill of Materials. Manifest of all models, training data, fine-tunes, tools. OWASP and IBM driving standards.' },
  'aws-well-architected-genai-lens': { front: 'AWS Well-Architected GenAI Lens', back: 'AWS reference architecture for GenAI workloads. Responsible AI Lens added re:Invent 2025.' },
  'build-vs-buy-framework': { front: 'Build vs buy framework', back: 'Decision spectrum: full custom -> fine-tune open-weight -> RAG over API -> vendor SaaS -> hybrid. First architectural decision.' },
  'tco-for-ai-systems': { front: 'TCO for AI systems', back: 'Total cost: API/inference + storage + observability + headcount + change management. Hidden costs (engineering, ops) often dominate.' },
  'vendor-scorecard': { front: 'Vendor scorecard', back: 'Weighted matrix: data handling, security certifications, compliance, SLAs, pricing, API stability, audit logs, IP indemnification.' },
  'vendor-lock-in': { front: 'Vendor lock-in', back: 'Risk of vendor dependency. Mitigated by API portability (LiteLLM), embedding choice, prompt portability. Some lock-in is intentional.' },
  'klarna-case-study': { front: 'Klarna case study', back: 'Canonical cautionary tale: 700-FTE-equivalent AI assistant in 2024; quiet rehiring of humans by mid-2025. Customer experience needs hybrid design.' },
  'jpmorgan-coin-llm-suite': { front: 'JPMorgan COIN / LLM Suite', back: 'COIN saves 360K legal hours/year. LLM Suite reached 250K employees mid-2025; ~$1.5-2.5B annual value.' },
  'wells-fargo-fargo': { front: 'Wells Fargo Fargo', back: '245M interactions in 2024; 1B cumulative by March 2026. Architecture: zero PII to LLM, zero human handoffs.' },
  'walmart-4m-developer-hours': { front: 'Walmart 4M dev hours', back: 'FY24 savings from AI coding tools per CEO Doug McMillon. ~5% per-engineer; aggregates at 30K+ engineers to material business outcome.' },
  'booking-com-16-pr-uplift': { front: 'Booking.com 16% PR uplift', back: 'DX Core 4 measurement; 150K dev hours saved year one with 65% adoption. Rigorous instrumentation, not surveys.' },
  'kaiser-tpmg-ambient-ai': { front: 'Kaiser TPMG ambient AI', back: 'NEJM Catalyst June 2025: 15,791 documentation hours saved in 63 weeks via ambient AI scribing.' },
  'ai-center-of-excellence-coe': { front: 'AI Center of Excellence', back: 'Centralized team setting standards, building shared platforms, supporting BUs. Dominant 2026 AI org pattern.' },
  'hub-and-spoke-federated-centralized': { front: 'CoE operating models', back: 'Hub-and-spoke (dominant 2026), federated (high BU autonomy), centralized (small / early-stage). Pick by org maturity.' },
  'workflow-redesign': { front: 'Workflow redesign', back: 'McKinsey 2025: largest single correlate of EBIT impact from GenAI. Only 21% of organizations have done it.' },
  'ai-red-teaming': { front: 'AI red-teaming', back: 'Adversarial testing for safety, security, policy violations. Empirical practice of finding what AI products break under attack.' },
  'pyrit': { front: 'PyRIT', back: 'Microsoft\'s open-source AI red-teaming framework. Reference toolkit for systematic adversarial testing.' },
  'mitre-atlas': { front: 'MITRE ATLAS', back: 'Adversarial threat landscape for AI. v5.1 (Nov 2025) covers 16 tactics, 84 techniques. AI-specific ATT&CK.' },
  'owasp-llm-top-10-2025': { front: 'OWASP LLM Top 10 (2025)', back: 'Industry-standard LLM application vulnerabilities. Prompt injection, insecure output, training data poisoning, excessive agency, etc.' },
  'project-glasswing': { front: 'Project Glasswing', back: 'Anthropic-led defensive cybersecurity consortium (April 2026). Members: AWS, Apple, Google, Microsoft, JPMorgan, NVIDIA.' },
  'the-attacker-moves-second-thesis': { front: 'Attacker moves second thesis', back: 'Nasr et al. 2025: adaptive attackers bypass 12 published defenses with >90% success rate. Design for blast-radius limitation.' },
  'differential-privacy-federated-learning-homomorphic-encryption-confidential-computing': { front: 'Privacy-preserving ML toolkit', back: 'Differential privacy (output noise), federated learning (on-device training), homomorphic encryption (compute on encrypted data), confidential computing (hardware enclaves).' },
  'ip-indemnification': { front: 'IP indemnification', back: 'Vendor commitments to defend customers in copyright suits. Microsoft, OpenAI, Anthropic, Google all offer; conditional on safety features.' },
  'sovereign-ai': { front: 'Sovereign AI', back: 'Deployment with full data residency and operational independence. Anthropic Sovereign, Azure Government, AWS GovCloud.' },

  // ===== Module 12: Career & The Job Market =====
  'ai-solutions-engineer': { front: 'AI Solutions Engineer', back: 'Vendor-side consultative engineer paired with sales. Pre-sales SE archetype; KORE1 breaks lane comp at $130K-$215K base.' },
  'ai-solutions-architect': { front: 'AI Solutions Architect', back: 'Enterprise architect designing how an organization integrates AI. Spans models, infrastructure, governance, business outcomes.' },
  'ai-engineer-chip-huyen-framing': { front: 'AI Engineer (Huyen)', back: 'Chip Huyen\'s framing: production-oriented engineer building on top of foundation models. Top-down (start from API) vs ML\'s bottom-up.' },
  'applied-ai-engineer': { front: 'Applied AI Engineer', back: 'AI-native vendor\'s title for embedded customer-implementation engineer. Customer-facing build role.' },
  'ai-native-software-engineer': { front: 'AI Native Software Engineer', back: 'Accenture\'s emerging category: cloud-native engineer with hands-on agentic systems experience.' },
  'ai-product-manager': { front: 'AI Product Manager', back: 'PM specializing in AI features. Owns the eval-driven feedback loop, model-vs-product tradeoffs, customer trust.' },
  'ml-engineer-vs-ai-engineer': { front: 'ML Engineer vs AI Engineer', back: 'ML Engineering: bottom-up (collect data, train, deploy). AI Engineering: top-down (start from API, layer abstractions).' },
  'ai-evaluation-engineer': { front: 'AI Evaluation Engineer', back: 'Eval-focused role owning error analysis, LLM-as-judge alignment, CI/CD eval gating. The new "QA for AI".' },
  'agent-engineer': { front: 'Agent Engineer', back: 'Designs tool catalogs, MCP servers, memory architectures, multi-agent orchestration. The 2026 specialization.' },
  'ai-red-team-security-engineer': { front: 'AI Red Team / Security Engineer', back: 'Adversarial testing and AI-specific security. Probes for prompt injection, jailbreaks, data leakage.' },
  'ai-implementation-consultant': { front: 'AI Implementation Consultant', back: 'Big Four / consulting role: Deloitte AI&D, PwC AI, EY.ai, KPMG AI, Accenture Data & AI.' },
  'forward-deployed-engineer-fde': { front: 'Forward Deployed Engineer (FDE)', back: 'Embedded customer engineer; Palantir\'s archetype, now standard at AI labs. Lives at customer sites.' },
  'chief-ai-officer-caio': { front: 'Chief AI Officer (CAIO)', back: 'Executive owning enterprise AI strategy. ~60% of large organizations have one by 2026.' },
  'levels-fyi': { front: 'Levels.fyi', back: 'Canonical crowd-sourced compensation data source. Top-lab medians for AI roles tracked there.' },
  'built-in': { front: 'Built In', back: 'Dominant US AI-specific job board. Salary data and role postings concentrated in AI-native companies.' },
  'ai-premium': { front: 'AI premium', back: '15-40% comp premium AI-specialized roles command over equivalent generalist roles. Compresses as supply grows.' },
  'kore1-four-lane-breakdown': { front: 'KORE1 four-lane breakdown', back: 'Pre-sales SE ($130K-$215K base), FDE ($171K-$415K Palantir, $350K-$550K AI labs), AI/ML lab researcher, Big Four consultant.' },
  'top-lab-medians-levels-fyi-may-2026': { front: 'Top-lab medians (May 2026)', back: 'OpenAI SWE $795K, Anthropic SWE $600K, Palantir FDSE $215K, Glean $207K. Per Levels.fyi.' },
  'big-four-bands': { front: 'Big Four bands', back: 'AI Senior Consultant $130K-$170K base. Manager $145K-$218K. Director $200K-$300K+ plus performance.' },
  'anthropic-london-salaries': { front: 'Anthropic London salaries', back: 'Base £225K-£630K depending on level. The new European compensation ceiling for AI-lab work.' },
  'hiring-manager-rubric': { front: 'Hiring manager rubric', back: 'Implicit evaluation: tradeoffs fluency, eval methodology, customer empathy, agent design judgment.' },
  'ai-ml-systems-design-interview': { front: 'AI/ML systems design interview', back: 'Dominant 2026 round: design RAG, design an agent, design an eval pipeline. Replacing classical web-scale system design.' },
  'behavioral-tell-me-about-a-time-you-used-ai-to': { front: 'Behavioral: "Tell me about a time"', back: 'Standard 2026 behavioral question: "Tell me about a time you used AI to..." Demonstrate agentic fluency, not anecdotes.' },
  'take-home-assignment': { front: 'Take-home assignment', back: '48-72 hour build of a RAG / agent / eval pipeline. Deploy to public URL; 5-10 hour expected effort.' },
  'demo-round-solutions-engineer': { front: 'Demo round (SE)', back: '30-45 minute live demo against customer scenario plus objection handling. Standard SE final round.' },
  'the-mirror-pattern': { front: 'The "Mirror" pattern', back: 'Pieter Levels\' approach: public AI demos that compound into reusable assets. Each demo fuels the next opportunity.' },
  'ai-tinkerers': { front: 'AI Tinkerers', back: 'Global meetup network (220 cities, 103K+ members). Live-demo-only events; high-signal AI engineering community.' },
  'ai-engineer-world-s-fair-summit': { front: 'AI Engineer World\'s Fair / Summit', back: 'Flagship industry conferences (swyx + AI Engineer Foundation). 2026\'s hub for AI engineering practice.' },
  'recruiting-channels': { front: 'Recruiting channels', back: 'Built In, AIJobs.io, Wellfound, Y Combinator Work at a Startup, Pallet, NextNext.AI, AI-specialized recruiters.' },
  'hacker-news-who-s-hiring': { front: 'HN Who\'s Hiring', back: 'Monthly Hacker News thread; high-signal source for AI startup roles. Engineer-to-engineer signal vs recruiter noise.' },

  // ===== Module 13: Emerging Directions =====
  'agentic-ai-growth': { front: 'Agentic AI growth', back: 'Stanford AI Index 2026: agentic-AI skills jumped from 0.06% to 0.23% of job postings in 2025. Fastest-growing AI skill category.' },
  'reasoning-models': { front: 'Reasoning models', back: 'Models that pre-think before answering: OpenAI o-series, Claude with extended thinking, DeepSeek R1, Gemini 2.5 Thinking.' },
  'test-time-compute-scaling': { front: 'Test-time compute scaling', back: '2024-2026 paradigm: throw more inference compute at hard problems. Reasoning budget as a tunable axis.' },
  'state-space-models': { front: 'State-space models', back: 'Alternative architectures challenging the transformer\'s dominance for long context (Mamba, RWKV, Hyena). Linear-time scaling.' },
  'diffusion-language-models': { front: 'Diffusion language models', back: 'Applying diffusion (long used for images) to text generation. Emerging research direction; potentially higher parallelism.' },
  'multimodal-native-models': { front: 'Multimodal-native models', back: 'Models trained from scratch on text + image + audio + video as one stream, not bolted-on modalities.' },
  'open-weight-catching-up': { front: 'Open-weight catching up', back: 'Qwen, DeepSeek, Llama achieving GPT-4-class performance at near-zero marginal cost. Capability gap narrowed but not closed.' },
  'personal-ai-sovereignty': { front: 'Personal AI sovereignty', back: 'Growing capability and movement around running 70B+ models on personal hardware. Privacy and ownership as features.' },
  'sovereign-ai-nation-state-deployments': { front: 'Sovereign AI / nation-state', back: 'On-prem and sovereign-cloud frontier model access for governments and regulated industries. EU, India, Saudi Arabia, UK leading.' },
  'ai-standards-convergence': { front: 'AI standards convergence', back: 'ISO 42001 + NIST AI RMF + EU AI Act increasingly stackable. ~70% of documentation overlaps; cross-mappings emerging.' },
  'the-ai-productivity-paradox': { front: 'AI productivity paradox', back: 'Brynjolfsson research: productivity gains lag adoption 1-3 years; perceived productivity ahead of measured productivity.' },
  'ai-incident-sharing': { front: 'AI incident sharing', back: 'MITRE AI Incident Sharing initiative (Oct 2024) and the AVID community database. Sharing failures across organizations.' },

  // ===== Module 14: AI Coding Agents & IDE Integration =====
  'ai-coding-agent': { front: 'AI coding agent', back: 'AI tool that participates in code creation: from autocomplete (Copilot) to autonomous agent (Devin).' },
  'the-progressive-autonomy-ladder': { front: 'Progressive autonomy ladder', back: 'Suggest -> Assist -> Automate -> Autonomous. Determines what the engineer\'s job becomes; pick the right rung per task.' },
  'pair-programming-with-ai': { front: 'Pair programming with AI', back: '"AI as partner" mental model: you steer, AI executes, you verify. The 2026 default operating mode.' },
  'ai-as-junior-dev': { front: 'AI as junior dev', back: 'Mental model where AI handles bounded tasks under review. Makes you a tech lead; not a peer engineer.' },
  'ai-as-rubber-duck': { front: 'AI as rubber duck', back: 'Mental model where AI helps you think through a problem. Output may not be used; the value is in the conversation.' },
  'cursor': { front: 'Cursor', back: 'VSCode fork with deep AI integration. Dominant 2026 AI IDE. @-mention for context; agent mode for autonomous edits.' },
  'continue-dev': { front: 'Continue.dev', back: 'Open-source IDE extension. Multi-provider; local-friendly. Strong choice for OSS-conscious teams.' },
  'cline': { front: 'Cline', back: 'VSCode extension with explicit act-mode for autonomous edits. Tight loop between plan and execution.' },
  'aider': { front: 'Aider', back: 'Terminal coding agent with deep git awareness. "Git as the source of truth"; every change is a commit.' },
  'github-copilot': { front: 'GitHub Copilot', back: 'The original AI coding tool. Suggestions, chat, Workspaces. Default at most large orgs.' },
  'copilot-workspace': { front: 'Copilot Workspace', back: 'GitHub\'s agent-mode entry. Spec-driven development inside GitHub; natural fit for issue-to-PR flows.' },
  'windsurf': { front: 'Windsurf', back: 'Codeium\'s IDE with agent mode. Cursor competitor; tight integration with their codebase indexing.' },
  'codex-cli': { front: 'Codex CLI', back: 'OpenAI\'s command-line coding agent. Terminal-resident; competes with Claude Code.' },
  'gemini-cli': { front: 'Gemini CLI', back: 'Google\'s command-line coding agent. Gemini-aligned; integrates with GCP services.' },
  'qwen-code': { front: 'Qwen Code', back: 'Alibaba\'s open-weight coding agent. Useful for self-hosted coding workflows.' },
  'opencode': { front: 'OpenCode', back: 'Open-source alternative to Claude Code. Community-driven; rapid iteration.' },
  'devin': { front: 'Devin', back: 'Cognition\'s autonomous SWE agent. "Background coding agent" archetype; you assign tasks, it returns PRs.' },
  'replit-agent': { front: 'Replit Agent', back: 'Replit\'s agent that builds entire apps from prompts. End-to-end deploy on Replit infrastructure.' },
  'openai-codex-the-agent-not-the-cli': { front: 'OpenAI Codex (agent)', back: 'OpenAI\'s autonomous coding agent service (distinct from the CLI). Background-agent pattern; operates on real repos.' },
  'background-agent-autonomous-coding': { front: 'Background agent / autonomous coding', back: 'Pattern where you give the agent a task, walk away, return to a PR. Devin / Codex / Replit Agent archetype.' },
  'mention-pattern-cursor': { front: '@-mention pattern (Cursor)', back: 'Reference files, symbols, docs explicitly in the prompt. The cleanest way to give an agent precise context.' },
  'plan-then-execute-pattern-claude-code': { front: 'Plan-then-execute pattern', back: 'Claude Code pattern: agent proposes a plan, you approve, then execution happens. Adds a review gate before action.' },
  'spec-driven-development-with-agents': { front: 'Spec-driven development', back: 'Write the spec first; agent implements. Aligns with Skills "Inversion" pattern: define inputs / outputs, let agent build.' },
  'test-driven-development-with-agents': { front: 'TDD with agents', back: 'Tests first, agent makes them pass. Tight feedback loop; tests double as the spec.' },
  'diff-based-vs-whole-file-editing': { front: 'Diff-based vs whole-file editing', back: 'Diff-based: faster, cheaper. Whole-file: more reliable on large refactors. Tradeoff every coding agent makes.' },
  'codebase-indexing': { front: 'Codebase indexing', back: 'How agents search your code: semantic embeddings + symbol graphs. Enables @-mention by symbol, codebase-aware suggestions.' },
  'the-ai-is-junior-dev-review-discipline': { front: 'AI-is-junior-dev review discipline', back: 'Always read what the agent produced before merging. The 2026 default; bypass only on bounded boilerplate.' },
  'swe-bench': { front: 'SWE-bench', back: 'Standard benchmark for AI coding agents. Real GitHub issues from popular Python repos; success rate is the headline metric.' },
  'terminal-bench': { front: 'Terminal-bench', back: 'Benchmark for command-line agentic tasks. Success jumped from 20% (early 2025) to 70%+ (2026 frontier).' },
  'the-capability-frontier': { front: 'AI coding capability frontier', back: 'As of mid-2026: agents handle most well-scoped tasks autonomously; novel architecture and ambiguous specs still need humans.' },
  'token-cost-for-coding-agents': { front: 'Coding agent token cost', back: 'Coding workloads are token-heavy. Expect $20-200/mo personal subscriptions; multiplies with autonomous background agents.' },
  'personal-subscription-tier-landscape': { front: 'Personal subscription tier landscape', back: 'Cursor Pro, Claude Pro / Max, GitHub Copilot Pro, Continue free + paid. Stacking 2-3 is common.' },

  // ===== Module 15: AI Product Design Patterns =====
  'manual': { front: 'Manual', back: 'Human does everything; AI not involved. Baseline against which AI features are measured.' },
  'suggest': { front: 'Suggest', back: 'AI proposes, human accepts or rejects. Copilot, Grammarly. Lowest autonomy on the ladder.' },
  'assist': { front: 'Assist', back: 'AI does the work, human supervises. Cursor agent mode. Mid-autonomy; human still owns each step.' },
  'automate': { front: 'Automate', back: 'AI handles defined workflows end-to-end; human in the loop on exceptions. Operations-grade autonomy.' },
  'autonomous': { front: 'Autonomous', back: 'AI runs without human review for individual steps. Human owns outcomes. Devin, Replit Agent, autonomous research.' },
  'copilot-pattern': { front: 'Copilot pattern', back: 'Suggestion-based; user remains the protagonist. GitHub Copilot, Microsoft Copilot. User does the steering.' },
  'autopilot-pattern': { front: 'Autopilot pattern', back: 'Autonomous execution with user review at boundaries. Replit Agent, Devin. AI does the steering with checkpoints.' },
  'generator-pattern': { front: 'Generator pattern (product)', back: 'The output is the product. Midjourney, Suno, Sora. Iterate to a satisfying artifact.' },
  'rewriter-pattern': { front: 'Rewriter pattern', back: 'Transform existing input. Grammarly rewrite, ChatGPT "improve this". Input + transformation = output.' },
  'summarizer-pattern': { front: 'Summarizer pattern', back: 'Compress long content. Meeting summaries, paper TL;DRs. Faithful compression is the success criterion.' },
  'classifier-pattern': { front: 'Classifier pattern', back: 'Categorize input into predefined buckets. Sentiment, intent, support routing. Often deterministic enough for Haiku-tier models.' },
  'extractor-pattern': { front: 'Extractor pattern', back: 'Structured data from unstructured input. Invoice fields, contract clauses. Pair with Pydantic / structured output.' },
  'conversational-interface-pattern': { front: 'Conversational interface pattern', back: 'Multi-turn dialogue as primary UX. ChatGPT, Claude.ai. Memory and context-management complexity.' },
  'embedded-suggest-pattern': { front: 'Embedded suggest pattern', back: 'Inline suggestions inside another tool. Grammarly in Gmail, Copilot in VSCode. Lowest-friction AI surfacing.' },
  'agent-pattern': { front: 'Agent pattern (product)', back: 'Multi-step autonomous task completion. Devin, Replit Agent, customer-support agents.' },
  'search-pattern': { front: 'Search pattern (AI product)', back: 'AI-augmented search over private corpora. Glean, Hebbia, AlphaSense. RAG productized.' },
  'q-a-pattern': { front: 'Q&A pattern', back: 'Question answering over documents. Legal Q&A, support docs. Trust hinges on faithful citations.' },
  'knowledge-worker-copilot': { front: 'Knowledge worker copilot', back: 'Productivity-suite-resident AI. M365 Copilot, Workspace Gemini. Embedded into existing workflows.' },
  'vertical-ai-assistant': { front: 'Vertical AI assistant', back: 'Domain-specific AI products. Harvey (legal), Abridge (clinical), Ambient AI. Deep workflow integration over horizontal generality.' },
  'ai-as-feature-vs-ai-as-product': { front: 'AI as feature vs AI as product', back: 'Is AI an enhancement to your existing product or the entire product? Different design, different defensibility.' },
  'the-trust-building-loop': { front: 'Trust-building loop', back: 'Cite sources, explain reasoning, allow correction. Standard pattern for AI products on serious workflows.' },
  'the-fallback-pattern': { front: 'Fallback pattern', back: 'How the product behaves when AI fails. Graceful degradation, human handoff. Determines crisis-day UX.' },
  'cost-shape-of-product': { front: 'Cost-shape-of-product', back: 'Per-seat vs per-token vs hybrid pricing. Determines what kind of usage is sustainable for your unit economics.' },
  'the-model-swap-architecture': { front: 'Model-swap architecture', back: 'Designing for model-agnostic interfaces so you can swap providers without rebuilding. Hedge against vendor lock-in.' },
  'latency-budgets-per-pattern': { front: 'Latency budgets per pattern', back: 'Conversational < 2s perceived; voice < 800ms; autocomplete < 100ms. Design choices flow from these caps.' },
  'streaming-as-ux': { front: 'Streaming as UX', back: 'Token-by-token streaming makes long generations feel fast. Canonical pattern; expected by users on chat-style products.' },
  'citation-and-source-visibility': { front: 'Citation and source visibility', back: 'RAG products must show where answers came from to build trust. Faithful citation > faithful answer alone.' },
  'edit-friendly-outputs': { front: 'Edit-friendly outputs', back: 'Outputs the user can refine (rich text, structured fields) outperform locked outputs. Editing is the trust-building act.' },
  'the-undo-regenerate-pattern': { front: 'Undo / regenerate pattern', back: 'Always provide a way to dismiss or rerun AI output. Trust foundation; lowers commitment-to-try barrier.' },

  // ===== Module 16: Data Engineering for AI =====
  'document-processing-pipeline': { front: 'Document processing pipeline', back: 'Ingest -> parse -> extract -> chunk -> embed -> index. The plumbing of every RAG system.' },
  'ocr': { front: 'OCR', back: 'Optical Character Recognition. Converting images of text into actual text. Foundation for any document-based RAG.' },
  'mistral-ocr': { front: 'Mistral OCR', back: 'Mistral\'s 2025 OCR API. Strong on layout and tables; competitive with Google / AWS at lower cost.' },
  'anthropic-vision-ocr': { front: 'Anthropic vision OCR', back: 'Claude\'s native vision capability used for OCR. Layout-aware extraction; reasoning over the document inline.' },
  'google-document-ai': { front: 'Google Document AI', back: 'GCP\'s document processing service. Pre-trained processors for forms, invoices, contracts, US tax documents.' },
  'azure-document-intelligence': { front: 'Azure Document Intelligence', back: 'Microsoft\'s document processing service. Form Recognizer evolution; tight Microsoft ecosystem fit.' },
  'aws-textract': { front: 'AWS Textract', back: 'AWS\'s OCR + structured extraction service. Native S3 integration; common in AWS-aligned stacks.' },
  'tesseract': { front: 'Tesseract', back: 'Open-source classical OCR. Still useful for simple text-on-image cases; outclassed by VLM-based approaches on layout.' },
  'layoutlm': { front: 'LayoutLM', back: 'Microsoft\'s family of layout-aware document understanding models. Joint text + position + image embeddings.' },
  'multimodal-extraction': { front: 'Multimodal extraction', back: 'Pulling tables, forms, handwriting, charts from documents using VLMs. The 2026 frontier; replacing classical pipelines.' },
  'entity-extraction': { front: 'Entity extraction', back: 'Identifying people, places, organizations, dates from text. Foundation of structured-data and graph-RAG pipelines.' },
  'relation-extraction': { front: 'Relation extraction', back: 'Identifying relationships between entities (subject-predicate-object). Builds the edges of a knowledge graph.' },
  'knowledge-graph-construction': { front: 'Knowledge graph construction', back: 'Building queryable graphs from extracted entities and relations. Foundation of GraphRAG.' },
  'structured-data-extraction': { front: 'Structured data extraction', back: 'Pulling specific fields (amounts, dates, names) into structured records. Pair with Pydantic / structured output.' },
  'unstructured-io': { front: 'Unstructured.io', back: 'Open-source library + commercial product for document parsing across 25+ formats. Default 2026 ingestion layer.' },
  'web-scraping-for-ai': { front: 'Web scraping for AI', back: 'Acquiring web content as training or retrieval data. Legal and ethical considerations: copyright, ToS, rate limits.' },
  'firecrawl': { front: 'Firecrawl', back: 'AI-friendly web scraper. Markdown output, structured extraction, agent-ready format.' },
  'crawl4ai': { front: 'Crawl4AI', back: 'Open-source AI-optimized scraper. LLM-ready output formats; growing 2026 OSS choice.' },
  'browse-ai': { front: 'Browse.ai', back: 'No-code scraper with AI-assisted setup. Lowers barrier for non-engineering teams to build scrapers.' },
  'scrapingbee': { front: 'ScrapingBee', back: 'Managed scraping API for harder targets. Handles JS rendering, proxies, captchas as a service.' },
  'data-labeling-platforms': { front: 'Data labeling platforms', back: 'Scale AI, Surge, Pareto.AI. Where humans annotate at scale for fine-tuning data and eval ground truth.' },
  'dataset-versioning': { front: 'Dataset versioning', back: 'Tools like DVC, Pachyderm. Treat datasets as code: every training run pinned to a hashed dataset.' },
  'data-validation': { front: 'Data validation', back: 'Great Expectations, Soda. Assertions about data shape; catch corruption before it reaches training or inference.' },
  'apache-spark-for-ai-workloads': { front: 'Apache Spark for AI', back: 'Distributed compute for large-scale data prep. Still common at enterprise scale; less dominant than five years ago.' },
  'dlt': { front: 'dlt', back: 'Open-source Python library for data pipelines. Rising in 2026 for declarative, lightweight ETL into AI stacks.' },
  'feature-stores': { front: 'Feature stores', back: 'Feast, Tecton. Serve features consistently to training and inference; avoids train-serve skew.' },
  'experiment-tracking': { front: 'Experiment tracking', back: 'Weights & Biases, MLflow, Comet. Track runs, hyperparameters, metrics. Standard for any non-trivial fine-tune.' },
  'weights-biases-w-b': { front: 'Weights & Biases', back: 'Dominant experiment-tracking platform. Broad adoption at AI labs; SaaS or self-hosted.' },
  'mlflow': { front: 'MLflow', back: 'Open-source experiment tracking + model registry. Common at enterprise; integrates with Databricks, Spark.' }
};
